package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"
	"strings"

	"github.com/go-openapi/swag"
)

// StartSearchURL generates an URL for the start search operation
type StartSearchURL struct {
	AppName string

	Port *int32

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *StartSearchURL) WithBasePath(bp string) *StartSearchURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *StartSearchURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *StartSearchURL) Build() (*url.URL, error) {
	var result url.URL

	var _path = "/v1/peers/{appName}"

	appName := o.AppName
	if appName != "" {
		_path = strings.Replace(_path, "{appName}", appName, -1)
	} else {
		return nil, errors.New("AppName is required on StartSearchURL")
	}
	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/"
	}
	result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var port string
	if o.Port != nil {
		port = swag.FormatInt32(*o.Port)
	}
	if port != "" {
		qs.Set("port", port)
	}

	result.RawQuery = qs.Encode()

	return &result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *StartSearchURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *StartSearchURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *StartSearchURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on StartSearchURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on StartSearchURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *StartSearchURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
