// Code generated by protoc-gen-go. DO NOT EDIT.
// source: discovery/pb/protocol.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	discovery/pb/protocol.proto

It has these top-level messages:
	Hearbeat
	PeerInfo
	Transfer
	Message
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Hearbeat struct {
}

func (m *Hearbeat) Reset()                    { *m = Hearbeat{} }
func (m *Hearbeat) String() string            { return proto.CompactTextString(m) }
func (*Hearbeat) ProtoMessage()               {}
func (*Hearbeat) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PeerInfo struct {
	Info map[string]string `protobuf:"bytes,2,rep,name=info" json:"info,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PeerInfo) Reset()                    { *m = PeerInfo{} }
func (m *PeerInfo) String() string            { return proto.CompactTextString(m) }
func (*PeerInfo) ProtoMessage()               {}
func (*PeerInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PeerInfo) GetInfo() map[string]string {
	if m != nil {
		return m.Info
	}
	return nil
}

type Transfer struct {
	Data string `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *Transfer) Reset()                    { *m = Transfer{} }
func (m *Transfer) String() string            { return proto.CompactTextString(m) }
func (*Transfer) ProtoMessage()               {}
func (*Transfer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Transfer) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type Message struct {
	Version int64 `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	// Types that are valid to be assigned to Msg:
	//	*Message_Heartbeat
	//	*Message_PeerInfo
	//	*Message_Transfer
	Msg isMessage_Msg `protobuf_oneof:"msg"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type isMessage_Msg interface {
	isMessage_Msg()
}

type Message_Heartbeat struct {
	Heartbeat *Hearbeat `protobuf:"bytes,2,opt,name=heartbeat,oneof"`
}
type Message_PeerInfo struct {
	PeerInfo *PeerInfo `protobuf:"bytes,3,opt,name=peerInfo,oneof"`
}
type Message_Transfer struct {
	Transfer *Transfer `protobuf:"bytes,4,opt,name=transfer,oneof"`
}

func (*Message_Heartbeat) isMessage_Msg() {}
func (*Message_PeerInfo) isMessage_Msg()  {}
func (*Message_Transfer) isMessage_Msg()  {}

func (m *Message) GetMsg() isMessage_Msg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *Message) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Message) GetHeartbeat() *Hearbeat {
	if x, ok := m.GetMsg().(*Message_Heartbeat); ok {
		return x.Heartbeat
	}
	return nil
}

func (m *Message) GetPeerInfo() *PeerInfo {
	if x, ok := m.GetMsg().(*Message_PeerInfo); ok {
		return x.PeerInfo
	}
	return nil
}

func (m *Message) GetTransfer() *Transfer {
	if x, ok := m.GetMsg().(*Message_Transfer); ok {
		return x.Transfer
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_Heartbeat)(nil),
		(*Message_PeerInfo)(nil),
		(*Message_Transfer)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// msg
	switch x := m.Msg.(type) {
	case *Message_Heartbeat:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Heartbeat); err != nil {
			return err
		}
	case *Message_PeerInfo:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeerInfo); err != nil {
			return err
		}
	case *Message_Transfer:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Transfer); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Msg has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 2: // msg.heartbeat
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Hearbeat)
		err := b.DecodeMessage(msg)
		m.Msg = &Message_Heartbeat{msg}
		return true, err
	case 3: // msg.peerInfo
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeerInfo)
		err := b.DecodeMessage(msg)
		m.Msg = &Message_PeerInfo{msg}
		return true, err
	case 4: // msg.transfer
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Transfer)
		err := b.DecodeMessage(msg)
		m.Msg = &Message_Transfer{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// msg
	switch x := m.Msg.(type) {
	case *Message_Heartbeat:
		s := proto.Size(x.Heartbeat)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_PeerInfo:
		s := proto.Size(x.PeerInfo)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Transfer:
		s := proto.Size(x.Transfer)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Hearbeat)(nil), "pb.Hearbeat")
	proto.RegisterType((*PeerInfo)(nil), "pb.PeerInfo")
	proto.RegisterType((*Transfer)(nil), "pb.Transfer")
	proto.RegisterType((*Message)(nil), "pb.Message")
}

func init() { proto.RegisterFile("discovery/pb/protocol.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 265 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xd7, 0x76, 0x73, 0xed, 0x9d, 0x0f, 0x12, 0x44, 0x82, 0x82, 0x8c, 0x3e, 0x8d, 0x21,
	0x1d, 0xcc, 0x07, 0xc5, 0x47, 0x41, 0xa8, 0x0f, 0x82, 0x04, 0xff, 0x40, 0xb2, 0xdd, 0xce, 0xe2,
	0x4c, 0x42, 0x12, 0x0b, 0xfd, 0x57, 0xfe, 0x44, 0x49, 0x6c, 0xd6, 0x97, 0x70, 0xee, 0x3d, 0x5f,
	0xc8, 0x39, 0x81, 0x9b, 0x7d, 0x6b, 0x77, 0xaa, 0x43, 0xd3, 0x6f, 0xb4, 0xd8, 0x68, 0xa3, 0x9c,
	0xda, 0xa9, 0x63, 0x15, 0x04, 0x49, 0xb5, 0x28, 0x01, 0xf2, 0x1a, 0xb9, 0x11, 0xc8, 0x5d, 0xa9,
	0x20, 0x7f, 0x47, 0x34, 0xaf, 0xb2, 0x51, 0x64, 0x0d, 0xd3, 0x56, 0x36, 0x8a, 0xa6, 0xcb, 0x6c,
	0xb5, 0xd8, 0x5e, 0x55, 0x5a, 0x54, 0xd1, 0xab, 0xfc, 0xf1, 0x22, 0x9d, 0xe9, 0x59, 0x60, 0xae,
	0x1f, 0xa0, 0x38, 0xad, 0xc8, 0x05, 0x64, 0x5f, 0xd8, 0xd3, 0x64, 0x99, 0xac, 0x0a, 0xe6, 0x25,
	0xb9, 0x84, 0x59, 0xc7, 0x8f, 0x3f, 0x48, 0xd3, 0xb0, 0xfb, 0x1f, 0x9e, 0xd2, 0xc7, 0xa4, 0xbc,
	0x85, 0xfc, 0xc3, 0x70, 0x69, 0x1b, 0x34, 0x84, 0xc0, 0x74, 0xcf, 0x1d, 0x1f, 0x2e, 0x06, 0x5d,
	0xfe, 0x26, 0x30, 0x7f, 0x43, 0x6b, 0xf9, 0x01, 0x09, 0x85, 0x79, 0x87, 0xc6, 0xb6, 0x4a, 0x06,
	0x24, 0x63, 0x71, 0x24, 0x77, 0x50, 0x7c, 0x22, 0x37, 0xce, 0x77, 0x08, 0x6f, 0x2c, 0xb6, 0xe7,
	0x3e, 0x6f, 0xec, 0x55, 0x4f, 0xd8, 0x08, 0x90, 0x35, 0xe4, 0x7a, 0x28, 0x42, 0xb3, 0x11, 0x8e,
	0xe5, 0xea, 0x09, 0x3b, 0xf9, 0x9e, 0x75, 0x43, 0x3e, 0x3a, 0x1d, 0xd9, 0x98, 0xd9, 0xb3, 0xd1,
	0x7f, 0x9e, 0x41, 0xf6, 0x6d, 0x0f, 0xe2, 0x2c, 0x7c, 0xed, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x00, 0xfb, 0xc7, 0x79, 0x01, 0x00, 0x00,
}
