// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pb/platform.proto

#ifndef PROTOBUF_pb_2fplatform_2eproto__INCLUDED
#define PROTOBUF_pb_2fplatform_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include "pb/matchmaking.pb.h"
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_pb_2fplatform_2eproto();
void protobuf_InitDefaults_pb_2fplatform_2eproto();
void protobuf_AssignDesc_pb_2fplatform_2eproto();
void protobuf_ShutdownFile_pb_2fplatform_2eproto();

class RPCHealthReply;
class RPCHealthRequest;
class RPCMessage;

// ===================================================================

class RPCHealthRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.RPCHealthRequest) */ {
 public:
  RPCHealthRequest();
  virtual ~RPCHealthRequest();

  RPCHealthRequest(const RPCHealthRequest& from);

  inline RPCHealthRequest& operator=(const RPCHealthRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const RPCHealthRequest& default_instance();

  static const RPCHealthRequest* internal_default_instance();

  void Swap(RPCHealthRequest* other);

  // implements Message ----------------------------------------------

  inline RPCHealthRequest* New() const { return New(NULL); }

  RPCHealthRequest* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RPCHealthRequest& from);
  void MergeFrom(const RPCHealthRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RPCHealthRequest* other);
  void UnsafeMergeFrom(const RPCHealthRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:pb.RPCHealthRequest)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_pb_2fplatform_2eproto_impl();
  friend void  protobuf_AddDesc_pb_2fplatform_2eproto_impl();
  friend void protobuf_AssignDesc_pb_2fplatform_2eproto();
  friend void protobuf_ShutdownFile_pb_2fplatform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RPCHealthRequest> RPCHealthRequest_default_instance_;

// -------------------------------------------------------------------

class RPCHealthReply : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.RPCHealthReply) */ {
 public:
  RPCHealthReply();
  virtual ~RPCHealthReply();

  RPCHealthReply(const RPCHealthReply& from);

  inline RPCHealthReply& operator=(const RPCHealthReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const RPCHealthReply& default_instance();

  static const RPCHealthReply* internal_default_instance();

  void Swap(RPCHealthReply* other);

  // implements Message ----------------------------------------------

  inline RPCHealthReply* New() const { return New(NULL); }

  RPCHealthReply* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RPCHealthReply& from);
  void MergeFrom(const RPCHealthReply& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RPCHealthReply* other);
  void UnsafeMergeFrom(const RPCHealthReply& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool ready = 1;
  void clear_ready();
  static const int kReadyFieldNumber = 1;
  bool ready() const;
  void set_ready(bool value);

  // optional string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:pb.RPCHealthReply)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::ArenaStringPtr message_;
  bool ready_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_pb_2fplatform_2eproto_impl();
  friend void  protobuf_AddDesc_pb_2fplatform_2eproto_impl();
  friend void protobuf_AssignDesc_pb_2fplatform_2eproto();
  friend void protobuf_ShutdownFile_pb_2fplatform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RPCHealthReply> RPCHealthReply_default_instance_;

// -------------------------------------------------------------------

class RPCMessage : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.RPCMessage) */ {
 public:
  RPCMessage();
  virtual ~RPCMessage();

  RPCMessage(const RPCMessage& from);

  inline RPCMessage& operator=(const RPCMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const RPCMessage& default_instance();

  enum MsgCase {
    kHealthRequest = 3,
    kHealthReply = 4,
    kUpsertSessionRequest = 5,
    kUpsertSessionResponse = 6,
    kGetSessionsRequest = 7,
    kGetSessionsResponse = 8,
    kDeleteSessionRequest = 9,
    kDeleteSessionResponse = 10,
    MSG_NOT_SET = 0,
  };

  static const RPCMessage* internal_default_instance();

  void Swap(RPCMessage* other);

  // implements Message ----------------------------------------------

  inline RPCMessage* New() const { return New(NULL); }

  RPCMessage* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RPCMessage& from);
  void MergeFrom(const RPCMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RPCMessage* other);
  void UnsafeMergeFrom(const RPCMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // optional int64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // optional .pb.RPCHealthRequest healthRequest = 3;
  bool has_healthrequest() const;
  void clear_healthrequest();
  static const int kHealthRequestFieldNumber = 3;
  const ::pb::RPCHealthRequest& healthrequest() const;
  ::pb::RPCHealthRequest* mutable_healthrequest();
  ::pb::RPCHealthRequest* release_healthrequest();
  void set_allocated_healthrequest(::pb::RPCHealthRequest* healthrequest);

  // optional .pb.RPCHealthReply HealthReply = 4;
  bool has_healthreply() const;
  void clear_healthreply();
  static const int kHealthReplyFieldNumber = 4;
  const ::pb::RPCHealthReply& healthreply() const;
  ::pb::RPCHealthReply* mutable_healthreply();
  ::pb::RPCHealthReply* release_healthreply();
  void set_allocated_healthreply(::pb::RPCHealthReply* healthreply);

  // optional .pb.RPCUpsertSessionRequest UpsertSessionRequest = 5;
  bool has_upsertsessionrequest() const;
  void clear_upsertsessionrequest();
  static const int kUpsertSessionRequestFieldNumber = 5;
  const ::pb::RPCUpsertSessionRequest& upsertsessionrequest() const;
  ::pb::RPCUpsertSessionRequest* mutable_upsertsessionrequest();
  ::pb::RPCUpsertSessionRequest* release_upsertsessionrequest();
  void set_allocated_upsertsessionrequest(::pb::RPCUpsertSessionRequest* upsertsessionrequest);

  // optional .pb.RPCUpsertSessionResponse UpsertSessionResponse = 6;
  bool has_upsertsessionresponse() const;
  void clear_upsertsessionresponse();
  static const int kUpsertSessionResponseFieldNumber = 6;
  const ::pb::RPCUpsertSessionResponse& upsertsessionresponse() const;
  ::pb::RPCUpsertSessionResponse* mutable_upsertsessionresponse();
  ::pb::RPCUpsertSessionResponse* release_upsertsessionresponse();
  void set_allocated_upsertsessionresponse(::pb::RPCUpsertSessionResponse* upsertsessionresponse);

  // optional .pb.RPCGetSessionsRequest GetSessionsRequest = 7;
  bool has_getsessionsrequest() const;
  void clear_getsessionsrequest();
  static const int kGetSessionsRequestFieldNumber = 7;
  const ::pb::RPCGetSessionsRequest& getsessionsrequest() const;
  ::pb::RPCGetSessionsRequest* mutable_getsessionsrequest();
  ::pb::RPCGetSessionsRequest* release_getsessionsrequest();
  void set_allocated_getsessionsrequest(::pb::RPCGetSessionsRequest* getsessionsrequest);

  // optional .pb.RPCGetSessionsResponse GetSessionsResponse = 8;
  bool has_getsessionsresponse() const;
  void clear_getsessionsresponse();
  static const int kGetSessionsResponseFieldNumber = 8;
  const ::pb::RPCGetSessionsResponse& getsessionsresponse() const;
  ::pb::RPCGetSessionsResponse* mutable_getsessionsresponse();
  ::pb::RPCGetSessionsResponse* release_getsessionsresponse();
  void set_allocated_getsessionsresponse(::pb::RPCGetSessionsResponse* getsessionsresponse);

  // optional .pb.RPCDeleteSessionRequest DeleteSessionRequest = 9;
  bool has_deletesessionrequest() const;
  void clear_deletesessionrequest();
  static const int kDeleteSessionRequestFieldNumber = 9;
  const ::pb::RPCDeleteSessionRequest& deletesessionrequest() const;
  ::pb::RPCDeleteSessionRequest* mutable_deletesessionrequest();
  ::pb::RPCDeleteSessionRequest* release_deletesessionrequest();
  void set_allocated_deletesessionrequest(::pb::RPCDeleteSessionRequest* deletesessionrequest);

  // optional .pb.RPCDeleteSessionResponse DeleteSessionResponse = 10;
  bool has_deletesessionresponse() const;
  void clear_deletesessionresponse();
  static const int kDeleteSessionResponseFieldNumber = 10;
  const ::pb::RPCDeleteSessionResponse& deletesessionresponse() const;
  ::pb::RPCDeleteSessionResponse* mutable_deletesessionresponse();
  ::pb::RPCDeleteSessionResponse* release_deletesessionresponse();
  void set_allocated_deletesessionresponse(::pb::RPCDeleteSessionResponse* deletesessionresponse);

  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:pb.RPCMessage)
 private:
  inline void set_has_healthrequest();
  inline void set_has_healthreply();
  inline void set_has_upsertsessionrequest();
  inline void set_has_upsertsessionresponse();
  inline void set_has_getsessionsrequest();
  inline void set_has_getsessionsresponse();
  inline void set_has_deletesessionrequest();
  inline void set_has_deletesessionresponse();

  inline bool has_msg() const;
  void clear_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::int64 version_;
  ::google::protobuf::int64 id_;
  union MsgUnion {
    MsgUnion() {}
    ::pb::RPCHealthRequest* healthrequest_;
    ::pb::RPCHealthReply* healthreply_;
    ::pb::RPCUpsertSessionRequest* upsertsessionrequest_;
    ::pb::RPCUpsertSessionResponse* upsertsessionresponse_;
    ::pb::RPCGetSessionsRequest* getsessionsrequest_;
    ::pb::RPCGetSessionsResponse* getsessionsresponse_;
    ::pb::RPCDeleteSessionRequest* deletesessionrequest_;
    ::pb::RPCDeleteSessionResponse* deletesessionresponse_;
  } msg_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_InitDefaults_pb_2fplatform_2eproto_impl();
  friend void  protobuf_AddDesc_pb_2fplatform_2eproto_impl();
  friend void protobuf_AssignDesc_pb_2fplatform_2eproto();
  friend void protobuf_ShutdownFile_pb_2fplatform_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RPCMessage> RPCMessage_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// RPCHealthRequest

inline const RPCHealthRequest* RPCHealthRequest::internal_default_instance() {
  return &RPCHealthRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// RPCHealthReply

// optional bool ready = 1;
inline void RPCHealthReply::clear_ready() {
  ready_ = false;
}
inline bool RPCHealthReply::ready() const {
  // @@protoc_insertion_point(field_get:pb.RPCHealthReply.ready)
  return ready_;
}
inline void RPCHealthReply::set_ready(bool value) {
  
  ready_ = value;
  // @@protoc_insertion_point(field_set:pb.RPCHealthReply.ready)
}

// optional string message = 2;
inline void RPCHealthReply::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RPCHealthReply::message() const {
  // @@protoc_insertion_point(field_get:pb.RPCHealthReply.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RPCHealthReply::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.RPCHealthReply.message)
}
inline void RPCHealthReply::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.RPCHealthReply.message)
}
inline void RPCHealthReply::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.RPCHealthReply.message)
}
inline ::std::string* RPCHealthReply::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb.RPCHealthReply.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RPCHealthReply::release_message() {
  // @@protoc_insertion_point(field_release:pb.RPCHealthReply.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RPCHealthReply::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb.RPCHealthReply.message)
}

inline const RPCHealthReply* RPCHealthReply::internal_default_instance() {
  return &RPCHealthReply_default_instance_.get();
}
// -------------------------------------------------------------------

// RPCMessage

// optional int64 version = 1;
inline void RPCMessage::clear_version() {
  version_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RPCMessage::version() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.version)
  return version_;
}
inline void RPCMessage::set_version(::google::protobuf::int64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:pb.RPCMessage.version)
}

// optional int64 id = 2;
inline void RPCMessage::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RPCMessage::id() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.id)
  return id_;
}
inline void RPCMessage::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:pb.RPCMessage.id)
}

// optional .pb.RPCHealthRequest healthRequest = 3;
inline bool RPCMessage::has_healthrequest() const {
  return msg_case() == kHealthRequest;
}
inline void RPCMessage::set_has_healthrequest() {
  _oneof_case_[0] = kHealthRequest;
}
inline void RPCMessage::clear_healthrequest() {
  if (has_healthrequest()) {
    delete msg_.healthrequest_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCHealthRequest& RPCMessage::healthrequest() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.healthRequest)
  return has_healthrequest()
      ? *msg_.healthrequest_
      : ::pb::RPCHealthRequest::default_instance();
}
inline ::pb::RPCHealthRequest* RPCMessage::mutable_healthrequest() {
  if (!has_healthrequest()) {
    clear_msg();
    set_has_healthrequest();
    msg_.healthrequest_ = new ::pb::RPCHealthRequest;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.healthRequest)
  return msg_.healthrequest_;
}
inline ::pb::RPCHealthRequest* RPCMessage::release_healthrequest() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.healthRequest)
  if (has_healthrequest()) {
    clear_has_msg();
    ::pb::RPCHealthRequest* temp = msg_.healthrequest_;
    msg_.healthrequest_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_healthrequest(::pb::RPCHealthRequest* healthrequest) {
  clear_msg();
  if (healthrequest) {
    set_has_healthrequest();
    msg_.healthrequest_ = healthrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.healthRequest)
}

// optional .pb.RPCHealthReply HealthReply = 4;
inline bool RPCMessage::has_healthreply() const {
  return msg_case() == kHealthReply;
}
inline void RPCMessage::set_has_healthreply() {
  _oneof_case_[0] = kHealthReply;
}
inline void RPCMessage::clear_healthreply() {
  if (has_healthreply()) {
    delete msg_.healthreply_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCHealthReply& RPCMessage::healthreply() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.HealthReply)
  return has_healthreply()
      ? *msg_.healthreply_
      : ::pb::RPCHealthReply::default_instance();
}
inline ::pb::RPCHealthReply* RPCMessage::mutable_healthreply() {
  if (!has_healthreply()) {
    clear_msg();
    set_has_healthreply();
    msg_.healthreply_ = new ::pb::RPCHealthReply;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.HealthReply)
  return msg_.healthreply_;
}
inline ::pb::RPCHealthReply* RPCMessage::release_healthreply() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.HealthReply)
  if (has_healthreply()) {
    clear_has_msg();
    ::pb::RPCHealthReply* temp = msg_.healthreply_;
    msg_.healthreply_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_healthreply(::pb::RPCHealthReply* healthreply) {
  clear_msg();
  if (healthreply) {
    set_has_healthreply();
    msg_.healthreply_ = healthreply;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.HealthReply)
}

// optional .pb.RPCUpsertSessionRequest UpsertSessionRequest = 5;
inline bool RPCMessage::has_upsertsessionrequest() const {
  return msg_case() == kUpsertSessionRequest;
}
inline void RPCMessage::set_has_upsertsessionrequest() {
  _oneof_case_[0] = kUpsertSessionRequest;
}
inline void RPCMessage::clear_upsertsessionrequest() {
  if (has_upsertsessionrequest()) {
    delete msg_.upsertsessionrequest_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCUpsertSessionRequest& RPCMessage::upsertsessionrequest() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.UpsertSessionRequest)
  return has_upsertsessionrequest()
      ? *msg_.upsertsessionrequest_
      : ::pb::RPCUpsertSessionRequest::default_instance();
}
inline ::pb::RPCUpsertSessionRequest* RPCMessage::mutable_upsertsessionrequest() {
  if (!has_upsertsessionrequest()) {
    clear_msg();
    set_has_upsertsessionrequest();
    msg_.upsertsessionrequest_ = new ::pb::RPCUpsertSessionRequest;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.UpsertSessionRequest)
  return msg_.upsertsessionrequest_;
}
inline ::pb::RPCUpsertSessionRequest* RPCMessage::release_upsertsessionrequest() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.UpsertSessionRequest)
  if (has_upsertsessionrequest()) {
    clear_has_msg();
    ::pb::RPCUpsertSessionRequest* temp = msg_.upsertsessionrequest_;
    msg_.upsertsessionrequest_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_upsertsessionrequest(::pb::RPCUpsertSessionRequest* upsertsessionrequest) {
  clear_msg();
  if (upsertsessionrequest) {
    set_has_upsertsessionrequest();
    msg_.upsertsessionrequest_ = upsertsessionrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.UpsertSessionRequest)
}

// optional .pb.RPCUpsertSessionResponse UpsertSessionResponse = 6;
inline bool RPCMessage::has_upsertsessionresponse() const {
  return msg_case() == kUpsertSessionResponse;
}
inline void RPCMessage::set_has_upsertsessionresponse() {
  _oneof_case_[0] = kUpsertSessionResponse;
}
inline void RPCMessage::clear_upsertsessionresponse() {
  if (has_upsertsessionresponse()) {
    delete msg_.upsertsessionresponse_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCUpsertSessionResponse& RPCMessage::upsertsessionresponse() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.UpsertSessionResponse)
  return has_upsertsessionresponse()
      ? *msg_.upsertsessionresponse_
      : ::pb::RPCUpsertSessionResponse::default_instance();
}
inline ::pb::RPCUpsertSessionResponse* RPCMessage::mutable_upsertsessionresponse() {
  if (!has_upsertsessionresponse()) {
    clear_msg();
    set_has_upsertsessionresponse();
    msg_.upsertsessionresponse_ = new ::pb::RPCUpsertSessionResponse;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.UpsertSessionResponse)
  return msg_.upsertsessionresponse_;
}
inline ::pb::RPCUpsertSessionResponse* RPCMessage::release_upsertsessionresponse() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.UpsertSessionResponse)
  if (has_upsertsessionresponse()) {
    clear_has_msg();
    ::pb::RPCUpsertSessionResponse* temp = msg_.upsertsessionresponse_;
    msg_.upsertsessionresponse_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_upsertsessionresponse(::pb::RPCUpsertSessionResponse* upsertsessionresponse) {
  clear_msg();
  if (upsertsessionresponse) {
    set_has_upsertsessionresponse();
    msg_.upsertsessionresponse_ = upsertsessionresponse;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.UpsertSessionResponse)
}

// optional .pb.RPCGetSessionsRequest GetSessionsRequest = 7;
inline bool RPCMessage::has_getsessionsrequest() const {
  return msg_case() == kGetSessionsRequest;
}
inline void RPCMessage::set_has_getsessionsrequest() {
  _oneof_case_[0] = kGetSessionsRequest;
}
inline void RPCMessage::clear_getsessionsrequest() {
  if (has_getsessionsrequest()) {
    delete msg_.getsessionsrequest_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCGetSessionsRequest& RPCMessage::getsessionsrequest() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.GetSessionsRequest)
  return has_getsessionsrequest()
      ? *msg_.getsessionsrequest_
      : ::pb::RPCGetSessionsRequest::default_instance();
}
inline ::pb::RPCGetSessionsRequest* RPCMessage::mutable_getsessionsrequest() {
  if (!has_getsessionsrequest()) {
    clear_msg();
    set_has_getsessionsrequest();
    msg_.getsessionsrequest_ = new ::pb::RPCGetSessionsRequest;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.GetSessionsRequest)
  return msg_.getsessionsrequest_;
}
inline ::pb::RPCGetSessionsRequest* RPCMessage::release_getsessionsrequest() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.GetSessionsRequest)
  if (has_getsessionsrequest()) {
    clear_has_msg();
    ::pb::RPCGetSessionsRequest* temp = msg_.getsessionsrequest_;
    msg_.getsessionsrequest_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_getsessionsrequest(::pb::RPCGetSessionsRequest* getsessionsrequest) {
  clear_msg();
  if (getsessionsrequest) {
    set_has_getsessionsrequest();
    msg_.getsessionsrequest_ = getsessionsrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.GetSessionsRequest)
}

// optional .pb.RPCGetSessionsResponse GetSessionsResponse = 8;
inline bool RPCMessage::has_getsessionsresponse() const {
  return msg_case() == kGetSessionsResponse;
}
inline void RPCMessage::set_has_getsessionsresponse() {
  _oneof_case_[0] = kGetSessionsResponse;
}
inline void RPCMessage::clear_getsessionsresponse() {
  if (has_getsessionsresponse()) {
    delete msg_.getsessionsresponse_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCGetSessionsResponse& RPCMessage::getsessionsresponse() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.GetSessionsResponse)
  return has_getsessionsresponse()
      ? *msg_.getsessionsresponse_
      : ::pb::RPCGetSessionsResponse::default_instance();
}
inline ::pb::RPCGetSessionsResponse* RPCMessage::mutable_getsessionsresponse() {
  if (!has_getsessionsresponse()) {
    clear_msg();
    set_has_getsessionsresponse();
    msg_.getsessionsresponse_ = new ::pb::RPCGetSessionsResponse;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.GetSessionsResponse)
  return msg_.getsessionsresponse_;
}
inline ::pb::RPCGetSessionsResponse* RPCMessage::release_getsessionsresponse() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.GetSessionsResponse)
  if (has_getsessionsresponse()) {
    clear_has_msg();
    ::pb::RPCGetSessionsResponse* temp = msg_.getsessionsresponse_;
    msg_.getsessionsresponse_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_getsessionsresponse(::pb::RPCGetSessionsResponse* getsessionsresponse) {
  clear_msg();
  if (getsessionsresponse) {
    set_has_getsessionsresponse();
    msg_.getsessionsresponse_ = getsessionsresponse;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.GetSessionsResponse)
}

// optional .pb.RPCDeleteSessionRequest DeleteSessionRequest = 9;
inline bool RPCMessage::has_deletesessionrequest() const {
  return msg_case() == kDeleteSessionRequest;
}
inline void RPCMessage::set_has_deletesessionrequest() {
  _oneof_case_[0] = kDeleteSessionRequest;
}
inline void RPCMessage::clear_deletesessionrequest() {
  if (has_deletesessionrequest()) {
    delete msg_.deletesessionrequest_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCDeleteSessionRequest& RPCMessage::deletesessionrequest() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.DeleteSessionRequest)
  return has_deletesessionrequest()
      ? *msg_.deletesessionrequest_
      : ::pb::RPCDeleteSessionRequest::default_instance();
}
inline ::pb::RPCDeleteSessionRequest* RPCMessage::mutable_deletesessionrequest() {
  if (!has_deletesessionrequest()) {
    clear_msg();
    set_has_deletesessionrequest();
    msg_.deletesessionrequest_ = new ::pb::RPCDeleteSessionRequest;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.DeleteSessionRequest)
  return msg_.deletesessionrequest_;
}
inline ::pb::RPCDeleteSessionRequest* RPCMessage::release_deletesessionrequest() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.DeleteSessionRequest)
  if (has_deletesessionrequest()) {
    clear_has_msg();
    ::pb::RPCDeleteSessionRequest* temp = msg_.deletesessionrequest_;
    msg_.deletesessionrequest_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_deletesessionrequest(::pb::RPCDeleteSessionRequest* deletesessionrequest) {
  clear_msg();
  if (deletesessionrequest) {
    set_has_deletesessionrequest();
    msg_.deletesessionrequest_ = deletesessionrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.DeleteSessionRequest)
}

// optional .pb.RPCDeleteSessionResponse DeleteSessionResponse = 10;
inline bool RPCMessage::has_deletesessionresponse() const {
  return msg_case() == kDeleteSessionResponse;
}
inline void RPCMessage::set_has_deletesessionresponse() {
  _oneof_case_[0] = kDeleteSessionResponse;
}
inline void RPCMessage::clear_deletesessionresponse() {
  if (has_deletesessionresponse()) {
    delete msg_.deletesessionresponse_;
    clear_has_msg();
  }
}
inline  const ::pb::RPCDeleteSessionResponse& RPCMessage::deletesessionresponse() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.DeleteSessionResponse)
  return has_deletesessionresponse()
      ? *msg_.deletesessionresponse_
      : ::pb::RPCDeleteSessionResponse::default_instance();
}
inline ::pb::RPCDeleteSessionResponse* RPCMessage::mutable_deletesessionresponse() {
  if (!has_deletesessionresponse()) {
    clear_msg();
    set_has_deletesessionresponse();
    msg_.deletesessionresponse_ = new ::pb::RPCDeleteSessionResponse;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.DeleteSessionResponse)
  return msg_.deletesessionresponse_;
}
inline ::pb::RPCDeleteSessionResponse* RPCMessage::release_deletesessionresponse() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.DeleteSessionResponse)
  if (has_deletesessionresponse()) {
    clear_has_msg();
    ::pb::RPCDeleteSessionResponse* temp = msg_.deletesessionresponse_;
    msg_.deletesessionresponse_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_deletesessionresponse(::pb::RPCDeleteSessionResponse* deletesessionresponse) {
  clear_msg();
  if (deletesessionresponse) {
    set_has_deletesessionresponse();
    msg_.deletesessionresponse_ = deletesessionresponse;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.DeleteSessionResponse)
}

inline bool RPCMessage::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void RPCMessage::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline RPCMessage::MsgCase RPCMessage::msg_case() const {
  return RPCMessage::MsgCase(_oneof_case_[0]);
}
inline const RPCMessage* RPCMessage::internal_default_instance() {
  return &RPCMessage_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_pb_2fplatform_2eproto__INCLUDED
