// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/messaging.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// DN messages
type DNDirectMessageResponse struct {
	Delivered bool `protobuf:"varint,1,opt,name=delivered" json:"delivered,omitempty"`
}

func (m *DNDirectMessageResponse) Reset()                    { *m = DNDirectMessageResponse{} }
func (m *DNDirectMessageResponse) String() string            { return proto.CompactTextString(m) }
func (*DNDirectMessageResponse) ProtoMessage()               {}
func (*DNDirectMessageResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *DNDirectMessageResponse) GetDelivered() bool {
	if m != nil {
		return m.Delivered
	}
	return false
}

type DNDirectMessageRequest struct {
	Message []byte `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *DNDirectMessageRequest) Reset()                    { *m = DNDirectMessageRequest{} }
func (m *DNDirectMessageRequest) String() string            { return proto.CompactTextString(m) }
func (*DNDirectMessageRequest) ProtoMessage()               {}
func (*DNDirectMessageRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *DNDirectMessageRequest) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// RPC messages
type RPCDirectMessage struct {
	PId     string `protobuf:"bytes,1,opt,name=pId" json:"pId,omitempty"`
	Message []byte `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *RPCDirectMessage) Reset()                    { *m = RPCDirectMessage{} }
func (m *RPCDirectMessage) String() string            { return proto.CompactTextString(m) }
func (*RPCDirectMessage) ProtoMessage()               {}
func (*RPCDirectMessage) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *RPCDirectMessage) GetPId() string {
	if m != nil {
		return m.PId
	}
	return ""
}

func (m *RPCDirectMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*DNDirectMessageResponse)(nil), "pb.DNDirectMessageResponse")
	proto.RegisterType((*DNDirectMessageRequest)(nil), "pb.DNDirectMessageRequest")
	proto.RegisterType((*RPCDirectMessage)(nil), "pb.RPCDirectMessage")
}

func init() { proto.RegisterFile("pb/messaging.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x48, 0xd2, 0xcf,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0xcf, 0xcc, 0x4b, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62,
	0x2a, 0x48, 0x52, 0x32, 0xe7, 0x12, 0x77, 0xf1, 0x73, 0xc9, 0x2c, 0x4a, 0x4d, 0x2e, 0xf1, 0x05,
	0x4b, 0xa7, 0x06, 0xa5, 0x16, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xc9, 0x70, 0x71, 0xa6, 0xa4,
	0xe6, 0x64, 0x96, 0xa5, 0x16, 0xa5, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x04, 0x21, 0x04,
	0x94, 0x8c, 0xb8, 0xc4, 0x30, 0x34, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x49, 0x70, 0xb1, 0x43,
	0x6c, 0x4a, 0x05, 0xeb, 0xe2, 0x09, 0x82, 0x71, 0x95, 0xec, 0xb8, 0x04, 0x82, 0x02, 0x9c, 0x51,
	0x34, 0x09, 0x09, 0x70, 0x31, 0x17, 0x78, 0x42, 0xcc, 0xe7, 0x0c, 0x02, 0x31, 0x91, 0xf5, 0x33,
	0xa1, 0xe8, 0x4f, 0x62, 0x03, 0xbb, 0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x03, 0xc0, 0x2c,
	0x43, 0xcd, 0x00, 0x00, 0x00,
}
