// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/platform.proto

package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type RPCHealthRequest struct {
	WaitForMinConnections bool `protobuf:"varint,1,opt,name=waitForMinConnections" json:"waitForMinConnections,omitempty"`
}

func (m *RPCHealthRequest) Reset()                    { *m = RPCHealthRequest{} }
func (m *RPCHealthRequest) String() string            { return proto.CompactTextString(m) }
func (*RPCHealthRequest) ProtoMessage()               {}
func (*RPCHealthRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{1} }

func (m *RPCHealthRequest) GetWaitForMinConnections() bool {
	if m != nil {
		return m.WaitForMinConnections
	}
	return false
}

type RPCHealthReply struct {
	Ready          bool   `protobuf:"varint,1,opt,name=ready" json:"ready,omitempty"`
	Message        string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	BasePath       string `protobuf:"bytes,3,opt,name=basePath" json:"basePath,omitempty"`
	NumConnections uint32 `protobuf:"varint,4,opt,name=numConnections" json:"numConnections,omitempty"`
}

func (m *RPCHealthReply) Reset()                    { *m = RPCHealthReply{} }
func (m *RPCHealthReply) String() string            { return proto.CompactTextString(m) }
func (*RPCHealthReply) ProtoMessage()               {}
func (*RPCHealthReply) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{2} }

func (m *RPCHealthReply) GetReady() bool {
	if m != nil {
		return m.Ready
	}
	return false
}

func (m *RPCHealthReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *RPCHealthReply) GetBasePath() string {
	if m != nil {
		return m.BasePath
	}
	return ""
}

func (m *RPCHealthReply) GetNumConnections() uint32 {
	if m != nil {
		return m.NumConnections
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "pb.empty")
	proto.RegisterType((*RPCHealthRequest)(nil), "pb.RPCHealthRequest")
	proto.RegisterType((*RPCHealthReply)(nil), "pb.RPCHealthReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Decentralizer service

type DecentralizerClient interface {
	//
	// Platform
	//
	// Get health of decentralizer.
	GetHealth(ctx context.Context, in *RPCHealthRequest, opts ...grpc.CallOption) (*RPCHealthReply, error)
	//
	// Matchmaking
	//
	// Create or update a session. Takes session info, returns session id.
	UpsertSession(ctx context.Context, in *RPCUpsertSessionRequest, opts ...grpc.CallOption) (*RPCUpsertSessionResponse, error)
	// Delete a session. Takes session id, returns bool informing if the deletion was a success
	DeleteSession(ctx context.Context, in *RPCDeleteSessionRequest, opts ...grpc.CallOption) (*RPCDeleteSessionResponse, error)
	// Get session ids. Takes session type, and a key and value to filter the sessions by details. If left empty this filter will not apply and all will be fetched.
	GetSessionIdsByDetails(ctx context.Context, in *RPCGetSessionIdsByDetailsRequest, opts ...grpc.CallOption) (*RPCGetSessionIdsResponse, error)
	// Get session ids. Takes peer ids. Returns session ids
	GetSessionIdsByPeerIds(ctx context.Context, in *RPCGetSessionIdsByPeerIdsRequest, opts ...grpc.CallOption) (*RPCGetSessionIdsResponse, error)
	// Get an individual session. Takes session id and returns session info.
	GetSession(ctx context.Context, in *RPCGetSessionRequest, opts ...grpc.CallOption) (*RPCGetSessionResponse, error)
	//
	// Address book
	//
	// Create or update a peer. Takes peer info, returns if it was a success.
	UpsertPeer(ctx context.Context, in *RPCUpsertPeerRequest, opts ...grpc.CallOption) (*RPCUpsertPeerResponse, error)
	// Get peer ids. takes a key and value to filter the peers by details. If left empty this filter will not apply and all will be fetched.
	GetPeerIds(ctx context.Context, in *RPCGetPeerIdsRequest, opts ...grpc.CallOption) (*RPCGetPeerIdsResponse, error)
	// Get an individual peer. Takes either a peer id or decentralizer id and returns the peer info.
	GetPeer(ctx context.Context, in *RPCGetPeerRequest, opts ...grpc.CallOption) (*RPCGetPeerResponse, error)
	//
	// Storage
	//
	// Write a peer file. Takes a file name and the data it should save.
	WritePeerFile(ctx context.Context, in *RPCWritePeerFileRequest, opts ...grpc.CallOption) (*RPCWritePeerFileResponse, error)
	// Get a peer file. Takes a file name, returns the file.
	GetPeerFile(ctx context.Context, in *RPCGetPeerFileRequest, opts ...grpc.CallOption) (*RPCGetPeerFileResponse, error)
	//
	// Messaging
	//
	// Send another peer a direct message. Takes a peer id and the data it should send
	SendDirectMessage(ctx context.Context, in *RPCDirectMessage, opts ...grpc.CallOption) (*Empty, error)
	ReceiveDirectMessage(ctx context.Context, in *RPCReceiveDirectMessageRequest, opts ...grpc.CallOption) (Decentralizer_ReceiveDirectMessageClient, error)
	//
	// Publisher
	//
	// Publish a new publisher update. (Only if you have the private key!)
	PublishPublisherUpdate(ctx context.Context, in *RPCPublishPublisherUpdateRequest, opts ...grpc.CallOption) (*Empty, error)
	// Get the full publisher definition
	GetPublisherDefinition(ctx context.Context, in *GetPublisherDefinitionRequest, opts ...grpc.CallOption) (*PublisherDefinition, error)
	// Get a publisher file.
	GetPublisherFile(ctx context.Context, in *RPCGetPublisherFileRequest, opts ...grpc.CallOption) (*RPCGetPublisherFileResponse, error)
}

type decentralizerClient struct {
	cc *grpc.ClientConn
}

func NewDecentralizerClient(cc *grpc.ClientConn) DecentralizerClient {
	return &decentralizerClient{cc}
}

func (c *decentralizerClient) GetHealth(ctx context.Context, in *RPCHealthRequest, opts ...grpc.CallOption) (*RPCHealthReply, error) {
	out := new(RPCHealthReply)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetHealth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) UpsertSession(ctx context.Context, in *RPCUpsertSessionRequest, opts ...grpc.CallOption) (*RPCUpsertSessionResponse, error) {
	out := new(RPCUpsertSessionResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/UpsertSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) DeleteSession(ctx context.Context, in *RPCDeleteSessionRequest, opts ...grpc.CallOption) (*RPCDeleteSessionResponse, error) {
	out := new(RPCDeleteSessionResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/DeleteSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetSessionIdsByDetails(ctx context.Context, in *RPCGetSessionIdsByDetailsRequest, opts ...grpc.CallOption) (*RPCGetSessionIdsResponse, error) {
	out := new(RPCGetSessionIdsResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetSessionIdsByDetails", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetSessionIdsByPeerIds(ctx context.Context, in *RPCGetSessionIdsByPeerIdsRequest, opts ...grpc.CallOption) (*RPCGetSessionIdsResponse, error) {
	out := new(RPCGetSessionIdsResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetSessionIdsByPeerIds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetSession(ctx context.Context, in *RPCGetSessionRequest, opts ...grpc.CallOption) (*RPCGetSessionResponse, error) {
	out := new(RPCGetSessionResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) UpsertPeer(ctx context.Context, in *RPCUpsertPeerRequest, opts ...grpc.CallOption) (*RPCUpsertPeerResponse, error) {
	out := new(RPCUpsertPeerResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/UpsertPeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetPeerIds(ctx context.Context, in *RPCGetPeerIdsRequest, opts ...grpc.CallOption) (*RPCGetPeerIdsResponse, error) {
	out := new(RPCGetPeerIdsResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetPeerIds", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetPeer(ctx context.Context, in *RPCGetPeerRequest, opts ...grpc.CallOption) (*RPCGetPeerResponse, error) {
	out := new(RPCGetPeerResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetPeer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) WritePeerFile(ctx context.Context, in *RPCWritePeerFileRequest, opts ...grpc.CallOption) (*RPCWritePeerFileResponse, error) {
	out := new(RPCWritePeerFileResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/WritePeerFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetPeerFile(ctx context.Context, in *RPCGetPeerFileRequest, opts ...grpc.CallOption) (*RPCGetPeerFileResponse, error) {
	out := new(RPCGetPeerFileResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetPeerFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) SendDirectMessage(ctx context.Context, in *RPCDirectMessage, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/SendDirectMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) ReceiveDirectMessage(ctx context.Context, in *RPCReceiveDirectMessageRequest, opts ...grpc.CallOption) (Decentralizer_ReceiveDirectMessageClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Decentralizer_serviceDesc.Streams[0], c.cc, "/pb.Decentralizer/ReceiveDirectMessage", opts...)
	if err != nil {
		return nil, err
	}
	x := &decentralizerReceiveDirectMessageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Decentralizer_ReceiveDirectMessageClient interface {
	Recv() (*RPCDirectMessage, error)
	grpc.ClientStream
}

type decentralizerReceiveDirectMessageClient struct {
	grpc.ClientStream
}

func (x *decentralizerReceiveDirectMessageClient) Recv() (*RPCDirectMessage, error) {
	m := new(RPCDirectMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *decentralizerClient) PublishPublisherUpdate(ctx context.Context, in *RPCPublishPublisherUpdateRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/publishPublisherUpdate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetPublisherDefinition(ctx context.Context, in *GetPublisherDefinitionRequest, opts ...grpc.CallOption) (*PublisherDefinition, error) {
	out := new(PublisherDefinition)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetPublisherDefinition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decentralizerClient) GetPublisherFile(ctx context.Context, in *RPCGetPublisherFileRequest, opts ...grpc.CallOption) (*RPCGetPublisherFileResponse, error) {
	out := new(RPCGetPublisherFileResponse)
	err := grpc.Invoke(ctx, "/pb.Decentralizer/GetPublisherFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Decentralizer service

type DecentralizerServer interface {
	//
	// Platform
	//
	// Get health of decentralizer.
	GetHealth(context.Context, *RPCHealthRequest) (*RPCHealthReply, error)
	//
	// Matchmaking
	//
	// Create or update a session. Takes session info, returns session id.
	UpsertSession(context.Context, *RPCUpsertSessionRequest) (*RPCUpsertSessionResponse, error)
	// Delete a session. Takes session id, returns bool informing if the deletion was a success
	DeleteSession(context.Context, *RPCDeleteSessionRequest) (*RPCDeleteSessionResponse, error)
	// Get session ids. Takes session type, and a key and value to filter the sessions by details. If left empty this filter will not apply and all will be fetched.
	GetSessionIdsByDetails(context.Context, *RPCGetSessionIdsByDetailsRequest) (*RPCGetSessionIdsResponse, error)
	// Get session ids. Takes peer ids. Returns session ids
	GetSessionIdsByPeerIds(context.Context, *RPCGetSessionIdsByPeerIdsRequest) (*RPCGetSessionIdsResponse, error)
	// Get an individual session. Takes session id and returns session info.
	GetSession(context.Context, *RPCGetSessionRequest) (*RPCGetSessionResponse, error)
	//
	// Address book
	//
	// Create or update a peer. Takes peer info, returns if it was a success.
	UpsertPeer(context.Context, *RPCUpsertPeerRequest) (*RPCUpsertPeerResponse, error)
	// Get peer ids. takes a key and value to filter the peers by details. If left empty this filter will not apply and all will be fetched.
	GetPeerIds(context.Context, *RPCGetPeerIdsRequest) (*RPCGetPeerIdsResponse, error)
	// Get an individual peer. Takes either a peer id or decentralizer id and returns the peer info.
	GetPeer(context.Context, *RPCGetPeerRequest) (*RPCGetPeerResponse, error)
	//
	// Storage
	//
	// Write a peer file. Takes a file name and the data it should save.
	WritePeerFile(context.Context, *RPCWritePeerFileRequest) (*RPCWritePeerFileResponse, error)
	// Get a peer file. Takes a file name, returns the file.
	GetPeerFile(context.Context, *RPCGetPeerFileRequest) (*RPCGetPeerFileResponse, error)
	//
	// Messaging
	//
	// Send another peer a direct message. Takes a peer id and the data it should send
	SendDirectMessage(context.Context, *RPCDirectMessage) (*Empty, error)
	ReceiveDirectMessage(*RPCReceiveDirectMessageRequest, Decentralizer_ReceiveDirectMessageServer) error
	//
	// Publisher
	//
	// Publish a new publisher update. (Only if you have the private key!)
	PublishPublisherUpdate(context.Context, *RPCPublishPublisherUpdateRequest) (*Empty, error)
	// Get the full publisher definition
	GetPublisherDefinition(context.Context, *GetPublisherDefinitionRequest) (*PublisherDefinition, error)
	// Get a publisher file.
	GetPublisherFile(context.Context, *RPCGetPublisherFileRequest) (*RPCGetPublisherFileResponse, error)
}

func RegisterDecentralizerServer(s *grpc.Server, srv DecentralizerServer) {
	s.RegisterService(&_Decentralizer_serviceDesc, srv)
}

func _Decentralizer_GetHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCHealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetHealth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetHealth(ctx, req.(*RPCHealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_UpsertSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCUpsertSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).UpsertSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/UpsertSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).UpsertSession(ctx, req.(*RPCUpsertSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCDeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/DeleteSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).DeleteSession(ctx, req.(*RPCDeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetSessionIdsByDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetSessionIdsByDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetSessionIdsByDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetSessionIdsByDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetSessionIdsByDetails(ctx, req.(*RPCGetSessionIdsByDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetSessionIdsByPeerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetSessionIdsByPeerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetSessionIdsByPeerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetSessionIdsByPeerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetSessionIdsByPeerIds(ctx, req.(*RPCGetSessionIdsByPeerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetSession(ctx, req.(*RPCGetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_UpsertPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCUpsertPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).UpsertPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/UpsertPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).UpsertPeer(ctx, req.(*RPCUpsertPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetPeerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetPeerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetPeerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetPeerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetPeerIds(ctx, req.(*RPCGetPeerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetPeer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetPeerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetPeer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetPeer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetPeer(ctx, req.(*RPCGetPeerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_WritePeerFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCWritePeerFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).WritePeerFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/WritePeerFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).WritePeerFile(ctx, req.(*RPCWritePeerFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetPeerFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetPeerFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetPeerFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetPeerFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetPeerFile(ctx, req.(*RPCGetPeerFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_SendDirectMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCDirectMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).SendDirectMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/SendDirectMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).SendDirectMessage(ctx, req.(*RPCDirectMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_ReceiveDirectMessage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RPCReceiveDirectMessageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DecentralizerServer).ReceiveDirectMessage(m, &decentralizerReceiveDirectMessageServer{stream})
}

type Decentralizer_ReceiveDirectMessageServer interface {
	Send(*RPCDirectMessage) error
	grpc.ServerStream
}

type decentralizerReceiveDirectMessageServer struct {
	grpc.ServerStream
}

func (x *decentralizerReceiveDirectMessageServer) Send(m *RPCDirectMessage) error {
	return x.ServerStream.SendMsg(m)
}

func _Decentralizer_PublishPublisherUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCPublishPublisherUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).PublishPublisherUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/PublishPublisherUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).PublishPublisherUpdate(ctx, req.(*RPCPublishPublisherUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetPublisherDefinition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublisherDefinitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetPublisherDefinition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetPublisherDefinition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetPublisherDefinition(ctx, req.(*GetPublisherDefinitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Decentralizer_GetPublisherFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCGetPublisherFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecentralizerServer).GetPublisherFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Decentralizer/GetPublisherFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecentralizerServer).GetPublisherFile(ctx, req.(*RPCGetPublisherFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Decentralizer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Decentralizer",
	HandlerType: (*DecentralizerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHealth",
			Handler:    _Decentralizer_GetHealth_Handler,
		},
		{
			MethodName: "UpsertSession",
			Handler:    _Decentralizer_UpsertSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _Decentralizer_DeleteSession_Handler,
		},
		{
			MethodName: "GetSessionIdsByDetails",
			Handler:    _Decentralizer_GetSessionIdsByDetails_Handler,
		},
		{
			MethodName: "GetSessionIdsByPeerIds",
			Handler:    _Decentralizer_GetSessionIdsByPeerIds_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _Decentralizer_GetSession_Handler,
		},
		{
			MethodName: "UpsertPeer",
			Handler:    _Decentralizer_UpsertPeer_Handler,
		},
		{
			MethodName: "GetPeerIds",
			Handler:    _Decentralizer_GetPeerIds_Handler,
		},
		{
			MethodName: "GetPeer",
			Handler:    _Decentralizer_GetPeer_Handler,
		},
		{
			MethodName: "WritePeerFile",
			Handler:    _Decentralizer_WritePeerFile_Handler,
		},
		{
			MethodName: "GetPeerFile",
			Handler:    _Decentralizer_GetPeerFile_Handler,
		},
		{
			MethodName: "SendDirectMessage",
			Handler:    _Decentralizer_SendDirectMessage_Handler,
		},
		{
			MethodName: "publishPublisherUpdate",
			Handler:    _Decentralizer_PublishPublisherUpdate_Handler,
		},
		{
			MethodName: "GetPublisherDefinition",
			Handler:    _Decentralizer_GetPublisherDefinition_Handler,
		},
		{
			MethodName: "GetPublisherFile",
			Handler:    _Decentralizer_GetPublisherFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReceiveDirectMessage",
			Handler:       _Decentralizer_ReceiveDirectMessage_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pb/platform.proto",
}

func init() { proto.RegisterFile("pb/platform.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 723 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x55, 0xed, 0x4e, 0xdb, 0x3c,
	0x14, 0x6e, 0x79, 0x5f, 0x5e, 0xc0, 0xa8, 0xbc, 0xe0, 0xb5, 0xa5, 0x74, 0x6c, 0x40, 0x86, 0x26,
	0xb6, 0x1f, 0x78, 0x5f, 0xda, 0x05, 0x8c, 0x8a, 0x0f, 0x0d, 0xa4, 0xaa, 0x0c, 0xf1, 0x6f, 0x93,
	0xd3, 0x1c, 0x5a, 0xab, 0x69, 0x62, 0x62, 0x97, 0xa9, 0x8b, 0xfa, 0x67, 0x9a, 0xb4, 0x0b, 0xd8,
	0x1d, 0xed, 0x16, 0x76, 0x0b, 0xbb, 0x90, 0x29, 0x8e, 0x1d, 0x12, 0x13, 0xa4, 0xfd, 0xf4, 0xf3,
	0x9c, 0xf3, 0x3c, 0xe7, 0xf1, 0x69, 0x5c, 0xb4, 0xc6, 0x5d, 0xc2, 0x7d, 0x2a, 0xaf, 0xc2, 0x68,
	0xbc, 0xcf, 0xa3, 0x50, 0x86, 0x78, 0x8e, 0xbb, 0xed, 0x3a, 0x77, 0xc9, 0x98, 0xca, 0xfe, 0x70,
	0x4c, 0x47, 0x2c, 0x18, 0xa4, 0x8c, 0x42, 0xa9, 0xe7, 0x45, 0x20, 0x84, 0x1b, 0x86, 0x23, 0x8d,
	0xae, 0x72, 0x97, 0x08, 0x19, 0x46, 0x74, 0x00, 0x1a, 0xc1, 0x49, 0x37, 0x08, 0x41, 0x07, 0xb7,
	0xbd, 0x09, 0xc6, 0x27, 0xae, 0xcf, 0xc4, 0x10, 0x22, 0x8d, 0x6d, 0x0e, 0xc2, 0x70, 0xe0, 0x03,
	0xa1, 0x9c, 0x11, 0x1a, 0x04, 0xa1, 0xa4, 0x92, 0x85, 0x81, 0x48, 0x59, 0x67, 0x01, 0xcd, 0xc3,
	0x98, 0xcb, 0xa9, 0x73, 0x8c, 0x56, 0x7b, 0xdd, 0x83, 0x63, 0xa0, 0xbe, 0x1c, 0xf6, 0xe0, 0x7a,
	0x02, 0x42, 0xe2, 0x37, 0xa8, 0xf1, 0x99, 0x32, 0x79, 0x18, 0x46, 0x67, 0x2c, 0x38, 0x08, 0x83,
	0x00, 0xfa, 0xaa, 0xb7, 0x55, 0xdd, 0xae, 0xee, 0x2d, 0xf6, 0xca, 0x49, 0xe7, 0x5b, 0x15, 0xad,
	0xe4, 0xa4, 0xb8, 0x3f, 0xc5, 0x75, 0x34, 0x1f, 0x01, 0xf5, 0xa6, 0xba, 0x31, 0x3d, 0xe0, 0x16,
	0x5a, 0x48, 0x03, 0x40, 0x6b, 0x6e, 0xbb, 0xba, 0xb7, 0xd4, 0x33, 0x47, 0xdc, 0x46, 0x8b, 0x2e,
	0x15, 0xd0, 0xa5, 0x72, 0xd8, 0xfa, 0x47, 0x51, 0xd9, 0x19, 0x3f, 0x45, 0x2b, 0xc1, 0x64, 0x9c,
	0x9f, 0xe6, 0xdf, 0xed, 0xea, 0x5e, 0xad, 0x67, 0xa1, 0xaf, 0x7e, 0x2e, 0xa3, 0x5a, 0x07, 0xfa,
	0x10, 0xc8, 0x88, 0xfa, 0xec, 0x0b, 0x44, 0x98, 0xa2, 0xa5, 0x23, 0x90, 0xe9, 0x5c, 0xb8, 0xbe,
	0xcf, 0xdd, 0x7d, 0x3b, 0x71, 0x1b, 0x5b, 0x28, 0xf7, 0xa7, 0xce, 0xf3, 0xaf, 0xbf, 0x7e, 0xff,
	0x98, 0xdb, 0xc5, 0x0e, 0xb9, 0x79, 0x49, 0x86, 0x8a, 0x20, 0x71, 0x69, 0xf4, 0x19, 0xfe, 0x84,
	0x6a, 0x17, 0x5c, 0x40, 0x24, 0xcf, 0x41, 0x08, 0x16, 0x06, 0xf8, 0xa1, 0x16, 0x2c, 0xa0, 0xc6,
	0x6d, 0xb3, 0x9c, 0x14, 0x3c, 0x0c, 0x04, 0x38, 0x0f, 0x94, 0x6f, 0xcd, 0x59, 0x4e, 0x7c, 0x85,
	0xd6, 0x3b, 0x4d, 0x42, 0xf9, 0x20, 0xc1, 0x36, 0x28, 0xa0, 0xb6, 0x81, 0x45, 0x6a, 0x83, 0x0a,
	0xfe, 0x5e, 0x45, 0xcd, 0x23, 0x30, 0xce, 0x27, 0x9e, 0x78, 0x37, 0xed, 0x80, 0xa4, 0xcc, 0x17,
	0x78, 0x57, 0xb7, 0x96, 0xd3, 0xb6, 0x41, 0xa1, 0x2a, 0x33, 0x78, 0xa6, 0x12, 0x3c, 0xc1, 0x3b,
	0xb9, 0x04, 0x82, 0xc4, 0x72, 0xca, 0x61, 0x46, 0xe2, 0x11, 0x4c, 0x67, 0x24, 0xbe, 0xa1, 0xfe,
	0x04, 0x66, 0xf8, 0xe3, 0x9d, 0x41, 0xba, 0x00, 0xd1, 0x89, 0x77, 0xef, 0x20, 0x9a, 0xfe, 0xbb,
	0x41, 0x2a, 0xd8, 0x45, 0xe8, 0x96, 0xc2, 0xad, 0x3b, 0xd5, 0x46, 0x67, 0xa3, 0x84, 0xd1, 0x22,
	0x5b, 0x2a, 0xcd, 0x06, 0x5e, 0xcf, 0xa5, 0x21, 0xb1, 0x30, 0x6e, 0x33, 0x7c, 0x80, 0x50, 0xba,
	0xc9, 0x64, 0xb6, 0xcc, 0xe3, 0x16, 0xb2, 0x3d, 0xf2, 0x8c, 0x35, 0xa8, 0x09, 0x9f, 0x1b, 0xd4,
	0x0a, 0xbc, 0x51, 0xc2, 0x94, 0x0d, 0xca, 0x01, 0x22, 0x61, 0x5d, 0xf6, 0x25, 0x5a, 0xd0, 0x6d,
	0xb8, 0x51, 0x94, 0x31, 0xea, 0x4d, 0x1b, 0xd6, 0xd2, 0x8f, 0x94, 0xf4, 0x3a, 0x6e, 0x18, 0x69,
	0x12, 0xf3, 0x13, 0x6f, 0x46, 0x62, 0x4f, 0xdd, 0xc0, 0x29, 0xaa, 0x5d, 0x46, 0x4c, 0x42, 0xd2,
	0x73, 0xc8, 0x7c, 0xc8, 0x7e, 0x9d, 0x05, 0xd4, 0xde, 0x99, 0x45, 0x66, 0x57, 0x71, 0x88, 0x96,
	0xb5, 0xbf, 0xd2, 0xb2, 0x12, 0xe7, 0x95, 0xda, 0x65, 0x54, 0xa6, 0xf3, 0x16, 0xad, 0x9d, 0x43,
	0xe0, 0x75, 0x58, 0x04, 0x7d, 0x79, 0xa6, 0x9f, 0x18, 0xf3, 0xfd, 0x17, 0xd0, 0xf6, 0x52, 0x82,
	0xa6, 0x0f, 0x62, 0x05, 0x7f, 0x40, 0xf5, 0x1e, 0xf4, 0x81, 0xdd, 0x40, 0xb1, 0xd5, 0xd1, 0xad,
	0x65, 0xa4, 0x99, 0xa8, 0x54, 0xde, 0xa9, 0xbc, 0xa8, 0xe2, 0xf7, 0xa8, 0xa9, 0x9f, 0xe8, 0xae,
	0x79, 0xa9, 0x2f, 0xb8, 0x47, 0x25, 0x64, 0xbf, 0xf4, 0x6e, 0x29, 0x6d, 0x94, 0x0b, 0x23, 0x8e,
	0xd4, 0x67, 0x93, 0x55, 0x76, 0xe0, 0x8a, 0x05, 0x2c, 0x79, 0x8b, 0xf0, 0x4e, 0x52, 0x56, 0xce,
	0x19, 0xa5, 0xf5, 0xa4, 0xa4, 0x84, 0x77, 0x1a, 0x6a, 0xcb, 0xff, 0xe3, 0x9a, 0xda, 0xb2, 0x29,
	0xc0, 0xd7, 0x68, 0x35, 0x2f, 0xa8, 0x96, 0xf2, 0x38, 0x77, 0xf3, 0x79, 0xc2, 0x78, 0x6c, 0xdd,
	0xcb, 0xeb, 0xf5, 0x6c, 0x2a, 0xaf, 0x26, 0xae, 0x17, 0xbc, 0x48, 0x1c, 0xd0, 0x31, 0xcc, 0xdc,
	0xff, 0xd4, 0xbf, 0xd4, 0xeb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc6, 0xcf, 0x12, 0x4e, 0x42,
	0x07, 0x00, 0x00,
}
