// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protocol.proto

#ifndef PROTOBUF_protocol_2eproto__INCLUDED
#define PROTOBUF_protocol_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_protocol_2eproto();
void protobuf_InitDefaults_protocol_2eproto();
void protobuf_AssignDesc_protocol_2eproto();
void protobuf_ShutdownFile_protocol_2eproto();

class HealthReply;
class HealthRequest;
class RPCMessage;

// ===================================================================

class HealthRequest : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.HealthRequest) */ {
 public:
  HealthRequest();
  virtual ~HealthRequest();

  HealthRequest(const HealthRequest& from);

  inline HealthRequest& operator=(const HealthRequest& from) {
    CopyFrom(from);
    return *this;
  }

  static const HealthRequest& default_instance();

  static const HealthRequest* internal_default_instance();

  void Swap(HealthRequest* other);

  // implements Message ----------------------------------------------

  inline HealthRequest* New() const { return New(NULL); }

  HealthRequest* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const HealthRequest& from);
  void MergeFrom(const HealthRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HealthRequest* other);
  void UnsafeMergeFrom(const HealthRequest& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:pb.HealthRequest)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<HealthRequest> HealthRequest_default_instance_;

// -------------------------------------------------------------------

class HealthReply : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.HealthReply) */ {
 public:
  HealthReply();
  virtual ~HealthReply();

  HealthReply(const HealthReply& from);

  inline HealthReply& operator=(const HealthReply& from) {
    CopyFrom(from);
    return *this;
  }

  static const HealthReply& default_instance();

  static const HealthReply* internal_default_instance();

  void Swap(HealthReply* other);

  // implements Message ----------------------------------------------

  inline HealthReply* New() const { return New(NULL); }

  HealthReply* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const HealthReply& from);
  void MergeFrom(const HealthReply& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(HealthReply* other);
  void UnsafeMergeFrom(const HealthReply& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional bool ready = 1;
  void clear_ready();
  static const int kReadyFieldNumber = 1;
  bool ready() const;
  void set_ready(bool value);

  // optional string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // @@protoc_insertion_point(class_scope:pb.HealthReply)
 private:

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::internal::ArenaStringPtr message_;
  bool ready_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<HealthReply> HealthReply_default_instance_;

// -------------------------------------------------------------------

class RPCMessage : public ::google::protobuf::MessageLite /* @@protoc_insertion_point(class_definition:pb.RPCMessage) */ {
 public:
  RPCMessage();
  virtual ~RPCMessage();

  RPCMessage(const RPCMessage& from);

  inline RPCMessage& operator=(const RPCMessage& from) {
    CopyFrom(from);
    return *this;
  }

  static const RPCMessage& default_instance();

  enum MsgCase {
    kHealthRequest = 3,
    kHealthReply = 4,
    MSG_NOT_SET = 0,
  };

  static const RPCMessage* internal_default_instance();

  void Swap(RPCMessage* other);

  // implements Message ----------------------------------------------

  inline RPCMessage* New() const { return New(NULL); }

  RPCMessage* New(::google::protobuf::Arena* arena) const;
  void CheckTypeAndMergeFrom(const ::google::protobuf::MessageLite& from);
  void CopyFrom(const RPCMessage& from);
  void MergeFrom(const RPCMessage& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  void DiscardUnknownFields();
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RPCMessage* other);
  void UnsafeMergeFrom(const RPCMessage& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _arena_ptr_;
  }
  inline ::google::protobuf::Arena* MaybeArenaPtr() const {
    return _arena_ptr_;
  }
  public:

  ::std::string GetTypeName() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 version = 1;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  ::google::protobuf::int64 version() const;
  void set_version(::google::protobuf::int64 value);

  // optional int64 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int64 id() const;
  void set_id(::google::protobuf::int64 value);

  // optional .pb.HealthRequest healthRequest = 3;
  bool has_healthrequest() const;
  void clear_healthrequest();
  static const int kHealthRequestFieldNumber = 3;
  const ::pb::HealthRequest& healthrequest() const;
  ::pb::HealthRequest* mutable_healthrequest();
  ::pb::HealthRequest* release_healthrequest();
  void set_allocated_healthrequest(::pb::HealthRequest* healthrequest);

  // optional .pb.HealthReply HealthReply = 4;
  bool has_healthreply() const;
  void clear_healthreply();
  static const int kHealthReplyFieldNumber = 4;
  const ::pb::HealthReply& healthreply() const;
  ::pb::HealthReply* mutable_healthreply();
  ::pb::HealthReply* release_healthreply();
  void set_allocated_healthreply(::pb::HealthReply* healthreply);

  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:pb.RPCMessage)
 private:
  inline void set_has_healthrequest();
  inline void set_has_healthreply();

  inline bool has_msg() const;
  void clear_msg();
  inline void clear_has_msg();

  ::google::protobuf::internal::ArenaStringPtr _unknown_fields_;
  ::google::protobuf::Arena* _arena_ptr_;

  ::google::protobuf::int64 version_;
  ::google::protobuf::int64 id_;
  union MsgUnion {
    MsgUnion() {}
    ::pb::HealthRequest* healthrequest_;
    ::pb::HealthReply* healthreply_;
  } msg_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend void  protobuf_InitDefaults_protocol_2eproto_impl();
  friend void  protobuf_AddDesc_protocol_2eproto_impl();
  friend void protobuf_AssignDesc_protocol_2eproto();
  friend void protobuf_ShutdownFile_protocol_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RPCMessage> RPCMessage_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// HealthRequest

inline const HealthRequest* HealthRequest::internal_default_instance() {
  return &HealthRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// HealthReply

// optional bool ready = 1;
inline void HealthReply::clear_ready() {
  ready_ = false;
}
inline bool HealthReply::ready() const {
  // @@protoc_insertion_point(field_get:pb.HealthReply.ready)
  return ready_;
}
inline void HealthReply::set_ready(bool value) {
  
  ready_ = value;
  // @@protoc_insertion_point(field_set:pb.HealthReply.ready)
}

// optional string message = 2;
inline void HealthReply::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& HealthReply::message() const {
  // @@protoc_insertion_point(field_get:pb.HealthReply.message)
  return message_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HealthReply::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pb.HealthReply.message)
}
inline void HealthReply::set_message(const char* value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pb.HealthReply.message)
}
inline void HealthReply::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pb.HealthReply.message)
}
inline ::std::string* HealthReply::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:pb.HealthReply.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* HealthReply::release_message() {
  // @@protoc_insertion_point(field_release:pb.HealthReply.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void HealthReply::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:pb.HealthReply.message)
}

inline const HealthReply* HealthReply::internal_default_instance() {
  return &HealthReply_default_instance_.get();
}
// -------------------------------------------------------------------

// RPCMessage

// optional int64 version = 1;
inline void RPCMessage::clear_version() {
  version_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RPCMessage::version() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.version)
  return version_;
}
inline void RPCMessage::set_version(::google::protobuf::int64 value) {
  
  version_ = value;
  // @@protoc_insertion_point(field_set:pb.RPCMessage.version)
}

// optional int64 id = 2;
inline void RPCMessage::clear_id() {
  id_ = GOOGLE_LONGLONG(0);
}
inline ::google::protobuf::int64 RPCMessage::id() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.id)
  return id_;
}
inline void RPCMessage::set_id(::google::protobuf::int64 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:pb.RPCMessage.id)
}

// optional .pb.HealthRequest healthRequest = 3;
inline bool RPCMessage::has_healthrequest() const {
  return msg_case() == kHealthRequest;
}
inline void RPCMessage::set_has_healthrequest() {
  _oneof_case_[0] = kHealthRequest;
}
inline void RPCMessage::clear_healthrequest() {
  if (has_healthrequest()) {
    delete msg_.healthrequest_;
    clear_has_msg();
  }
}
inline  const ::pb::HealthRequest& RPCMessage::healthrequest() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.healthRequest)
  return has_healthrequest()
      ? *msg_.healthrequest_
      : ::pb::HealthRequest::default_instance();
}
inline ::pb::HealthRequest* RPCMessage::mutable_healthrequest() {
  if (!has_healthrequest()) {
    clear_msg();
    set_has_healthrequest();
    msg_.healthrequest_ = new ::pb::HealthRequest;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.healthRequest)
  return msg_.healthrequest_;
}
inline ::pb::HealthRequest* RPCMessage::release_healthrequest() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.healthRequest)
  if (has_healthrequest()) {
    clear_has_msg();
    ::pb::HealthRequest* temp = msg_.healthrequest_;
    msg_.healthrequest_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_healthrequest(::pb::HealthRequest* healthrequest) {
  clear_msg();
  if (healthrequest) {
    set_has_healthrequest();
    msg_.healthrequest_ = healthrequest;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.healthRequest)
}

// optional .pb.HealthReply HealthReply = 4;
inline bool RPCMessage::has_healthreply() const {
  return msg_case() == kHealthReply;
}
inline void RPCMessage::set_has_healthreply() {
  _oneof_case_[0] = kHealthReply;
}
inline void RPCMessage::clear_healthreply() {
  if (has_healthreply()) {
    delete msg_.healthreply_;
    clear_has_msg();
  }
}
inline  const ::pb::HealthReply& RPCMessage::healthreply() const {
  // @@protoc_insertion_point(field_get:pb.RPCMessage.HealthReply)
  return has_healthreply()
      ? *msg_.healthreply_
      : ::pb::HealthReply::default_instance();
}
inline ::pb::HealthReply* RPCMessage::mutable_healthreply() {
  if (!has_healthreply()) {
    clear_msg();
    set_has_healthreply();
    msg_.healthreply_ = new ::pb::HealthReply;
  }
  // @@protoc_insertion_point(field_mutable:pb.RPCMessage.HealthReply)
  return msg_.healthreply_;
}
inline ::pb::HealthReply* RPCMessage::release_healthreply() {
  // @@protoc_insertion_point(field_release:pb.RPCMessage.HealthReply)
  if (has_healthreply()) {
    clear_has_msg();
    ::pb::HealthReply* temp = msg_.healthreply_;
    msg_.healthreply_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
inline void RPCMessage::set_allocated_healthreply(::pb::HealthReply* healthreply) {
  clear_msg();
  if (healthreply) {
    set_has_healthreply();
    msg_.healthreply_ = healthreply;
  }
  // @@protoc_insertion_point(field_set_allocated:pb.RPCMessage.HealthReply)
}

inline bool RPCMessage::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void RPCMessage::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline RPCMessage::MsgCase RPCMessage::msg_case() const {
  return RPCMessage::MsgCase(_oneof_case_[0]);
}
inline const RPCMessage* RPCMessage::internal_default_instance() {
  return &RPCMessage_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_protocol_2eproto__INCLUDED
